services:
  - type: web
    name: discord-google-bot
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PREFIX
        value: "!"
      - key: PORT
        value: "10000"
    healthCheckPath: /ping
