services:
  - type: web
    name: dis-chi-gg
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: DISCORD_TOKEN
        sync: false
      - key: PREFIX
        value: "!"
      - key: PORT
        value: "10000"